service:
  name: spike-serverless-neptune

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  vpc:
    securityGroupIds:
      - YOUR-SECURITY-GROUP-ID
    subnetIds:
      - YOUR-SUBNET-01
      - YOUR-SUBNET-02
  environment:
    NEPTUNE_ENDPOINT: ${env:NEPTUNE_ENDPOINT}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
